# config.yaml
server:
  port: "3001"
  log_level: "debug"
  jwt_secret: "supersecret"
  jwt_duration: 168
database:
  host: 127.0.0.1
  port: 5432
  user: sampleuser
  dbname: frens
  password: samplepassword
  sslmode: disable
storage:
  profile_pictures:
    type: local
    local:
      path: C:\\temp\\frens\\profile_pictures
    s3:
      bucket: frens-profile_pictures
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
  user_banners:
    type: local
    local:
      path: C:\\temp\\frens\\user_banners
    s3:
      bucket: frens-user_banners
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
  status_images:
    type: local
    local:
      path: C:\\temp\\frens\\status_images
    s3:
      bucket: frens-status_images
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
  status_videos:
    type: local
    local:
      path: C:\\temp\\frens\\status_videos
    s3:
      bucket: frens-status_videos
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
  status_audio:
    type: local
    local:
      path: C:\\temp\\frens\\status_audio
    s3:
      bucket: frens-status_audio
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
  status_files:
    type: local
    local:
      path: C:\\temp\\frens\\status_files
    s3:
      bucket: frens-status_files
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
