# config.yaml
server:
  port: "3001"
  log_level: "debug"
  jwt_secret: "supersecret"
  jwt_duration: 168
database:
  host: 127.0.0.1
  port: 5432
  user: sampleuser
  dbname: frens
  password: samplepassword
  sslmode: disable
  log_mode: true
storage:
  images:
    type: local
    local:
      path: C:\\temp\\frens\\images
    s3:
      bucket: frens-images
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
  video:
    type: local
    local:
      path: C:\\temp\\frens\\videos
    s3:
      bucket: frens-videos
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
  audio:
    type: local
    local:
      path: C:\\temp\\frens\\audio
    s3:
      bucket: frens-audio
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
  other:
    type: local
    local:
      path: C:\\temp\\frens\\other
    s3:
      bucket: frens-other
      region: us-east-1
      access_key: sampleaccesskey
      secret_key: samplesecretkey
