# config.yaml
server:
  port: "3001"
  jwt_secret: "supersecret"
  jwt_duration: 168
database:
  host: 127.0.0.1
  port: 5432
  user: sampleuser
  dbname: frens
  password: samplepassword
  sslmode: disable
