# config.yaml
server:
  base_url: "http://localhost:3001"
  port: "3001"
  log_level: "debug" #Options: debug, info, warn, error, fatal, panic
  jwt_secret: "supersecret"
  jwt_duration: 168
  allow_origins: true
database:
  host: 127.0.0.1
  port: 5432
  user: sampleuser
  dbname: frens
  password: samplepassword
  sslmode: disable
  log_mode: false
  max_idle_conns: 10
  max_open_conns: 100
storage:
  type: local
  local:
    path: C:\\temp\\frens
  s3:
    bucket: frens-images
    region: us-east-1
    access_key: sampleaccesskey
    secret_key: samplesecretkey