app:
  users:
    default_bio: "This user has not yet written a bio."

database:
  host: localhost
  port: "5432"
  name: frens
  user: user
  password: pass
  log_mode: true
  ssl_mode: disable
  dev_mode: false # For testing. This will wipe the database on startup. Do not use in production for obvious reasons.

handlers:
  port: "32500"
  token_secret: supersecret
  token_duration: 168

storage:
  type: local
  local:
    windows_path: C:\\temp\\frens
    linux_path: /tmp/frens
  s3:
    bucket: frens-images
    region: us-east-1
    access_key: sampleaccesskey
    secret_key: samplesecretkey
