definitions:
  response.Error:
    type: object
  response.Meta:
    properties:
      count:
        type: integer
    type: object
  response.Response:
    properties:
      data:
        description: Can be an array or a single data object
      errors:
        items:
          $ref: '#/definitions/response.Error'
        type: array
      included:
        description: Recursive types must be pointers
        items:
          $ref: '#/definitions/response.Response'
        type: array
      meta:
        $ref: '#/definitions/response.Meta'
    type: object
info:
  contact: {}
paths:
  /bookmarks/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a bookmark from a post
      parameters:
      - description: Bookmark ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete bookmark
      tags:
      - Bookmarks
    get:
      consumes:
      - application/json
      description: Retrieve a specific bookmark
      parameters:
      - description: Bookmark ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get bookmark
      tags:
      - Bookmarks
  /statuses/{id}/bookmarks:
    get:
      consumes:
      - application/json
      description: Retrieve bookmarks for a specific post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get post bookmarks
      tags:
      - Bookmarks
swagger: "2.0"
